FX_project/FX_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('test/', include('test_app.urls')),
  path('accounts/', include('django.contrib.auth.urls')),
  path('accounts/', include('accounts.urls')),
  path('',include('home.urls')),
  path('Note/',include('Note.urls')),
]

FX_project/Note/urls.py
from django.urls import path
from .views import history, chart_detail ,chart_index, histories2edit, chart_add, chart_update, chart_delete, chart_image, none2edit, chart_image_day, diary, calendar_index, diary_create, diary_update, diary_delete, chart_image_review, review, review_later, review_index, review_update, review_create, review_delete, speed_order, market_settlement, position_update

app_name = 'Note'

urlpatterns = [
    path('history/',history, name='history'),
    path('chart/index/',chart_index, name='chart_index'),
    path('chart/generate/',histories2edit, name='chart_generate'),
    path('chart/create/',none2edit, name='chart_create'),
    path('chart/add/',chart_add, name='chart_add'),
    path('chart/update/<int:id>',chart_update, name='chart_update'),
    path('chart/delete/<int:id>',chart_delete, name='chart_delete'),
    path('chart/detail/<int:id>',chart_detail, name='chart_detail'),
    path('chart/image/<int:id>',chart_image, name='chart_image'),
    path('chart/image/day/<str:pair>/<int:year>/<int:month>/<int:day>',chart_image_day, name='chart_image_day'),
    path('diary/<int:year>/<int:month>/<int:day>',diary, name='diary'),
    path('diary/<int:year>/<int:month>/<int:day>/<str:option>',diary, name='diary_option'),
    path('diary/create/<int:year>/<int:month>/<int:day>',diary_create, name='diary_create'),
    path('diary/update/<int:id>',diary_update, name='diary_update'),
    path('diary/delete/<int:id>',diary_delete, name='diary_delete'),
    path('calendar/<int:year>/<int:month>',calendar_index, name='calendar'),
    path('calendar/',calendar_index, name='calendar_now'),
    path('review/image/<int:id>',chart_image_review, name='chart_image_review'),
    path('review/',review_index, name='review_index'),
    path('review/<int:id>',review, name='review'),
    path('review/<int:id>/later/<str:delta>',review_later, name='review_later'),
    path('review/update/<int:id>',review_update, name='review_update'),
    path('review/create/',review_create, name='review_create'),
    path('review/delete/<int:id>',review_delete, name='review_delete'),
    path('review/<int:id>/position/',speed_order, name='speed_order'),  # ReviewTableのid
    path('review/position/<int:id>',market_settlement, name='market_settlement'),  # PositionTableのid
    path('review/position/<int:id>/update/',position_update, name='position_update'),  # PositionTableのid
]

FX_project/Note/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.utils import timezone

KIND = (("new","新規"),("settlement","決済"))
BUY_SELL = (("buy","買"),("sell","売"))
STATE = (("accepted","受付済"),("executed","約定済"),("canceled","取消済"))
# CONDITION = (("指値","limit"),("逆指値","stop"),("成行","market"))
CONDITION = (("limit","指値"),("stop","逆指値"),("market","成行"))
# RULE = (("1分足","1T"),("3分足","3T"),("15分足","15T"))
RULE = (
  ("1T","1分足"),
  ("3T","3分足"),
  ("5T","5分足"),
  ("10T","10分足"),
  ("15T","15分足"),
  ("30T","30分足"),
  ("1H","1時間足"),
  ("4H","4時間足"),
  ("D","日足"),
)
PAIR = (
  ("USD/JPY", "USD/JPY"),
  ("EUR/JPY","EUR/JPY"),
  ("EUR/USD","EUR/USD"),
  ("GBP/JPY","GBP/JPY"),
  ("AUD/JPY","AUD/JPY")
)

class HistoryTable(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  account = models.CharField(max_length=50)
  order_number = models.IntegerField()
  pair = models.CharField(max_length=10)  # choicesは利用しない
  order_type  = models.CharField(max_length=20)
  kind = models.CharField(max_length=10, choices=KIND)
  buy_sell = models.CharField(max_length=10, choices=BUY_SELL)
  quantity = models.FloatField()
  state = models.CharField(max_length=10, choices=STATE)
  revocation_reason = models.CharField(max_length=10, null=True, blank=True)  # 失効理由(ほぼOCO)
  order_datetime = models.DateTimeField()
  order_rate = models.FloatField(null=True, blank=True)
  condition = models.CharField(max_length=10, choices=CONDITION)
  execution_datetime = models.DateTimeField(null=True, blank=True)
  execution_rate = models.FloatField(null=True, blank=True)
  unit = models.CharField(max_length=10,default="JPY")
  profit = models.FloatField(null=True, blank=True)
  swap = models.FloatField(null=True, blank=True)
  memo = models.CharField(max_length=511)
  class Meta:
    constraints = [
      models.UniqueConstraint(
        fields=["user", "account", "order_number"],
        name="history_unique"
      )
    ]
  
def default_chart_name():
    last_review = ReviewTable.objects.last()
    next_id = last_review.id + 1 if last_review else 1
    return f"チャート（{next_id}）"

class ChartTable(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  # name = models.CharField(max_length=255, default=timezone.datetime.now().strftime("%Y/%m/%d %H:%M:%S"))
  name = models.CharField(max_length=255, default=default_chart_name)
  pair = models.CharField(max_length=10, choices=PAIR)
  rule = models.CharField(max_length=10, choices=RULE)
  standard_datetime = models.DateTimeField()
  minus_delta = models.IntegerField(default=100)
  plus_delta = models.IntegerField(default=100)
  memo = models.TextField(null=True, blank=True)

class HistoryLinkTable(models.Model):
  chart = models.ForeignKey(ChartTable, on_delete=models.CASCADE)
  history = models.ForeignKey(HistoryTable, on_delete=models.CASCADE)

class DiaryTable(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  date = models.DateField(unique=True)
  text = models.CharField(max_length=2047,null=True, blank=True)
  class Meta:
    constraints = [
      models.UniqueConstraint(
        fields=["user", "date"],
        name="date_unique"
      )
    ]


def default_review_name():
    last_review = ReviewTable.objects.last()
    next_id = last_review.id + 1 if last_review else 1
    return f"レビュー（{next_id}）"

class ReviewTable(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  # name = models.CharField(max_length=255, default=timezone.datetime.now().strftime("%Y/%m/%d %H:%M:%S"))
  name = models.CharField(max_length=255, default=default_review_name)
  pair = models.CharField(default="USD/JPY", max_length=10, choices=PAIR)
  rule = models.CharField(default="15T", max_length=10, choices=RULE)
  delta = models.IntegerField(default=150)
  dt = models.DateTimeField()
  memo = models.CharField(max_length=511,null=True, blank=True)

class PositionTable(models.Model):
  review = models.ForeignKey(ReviewTable, on_delete=models.CASCADE)
  pair = models.CharField(max_length=10, choices=PAIR)
  quantity = models.FloatField()
  buy_sell = models.CharField(max_length=10, choices=BUY_SELL)
  position_datetime = models.DateTimeField()
  position_rate = models.FloatField()
  condition = models.CharField(max_length=10, choices=CONDITION, null=True, blank=True)
  limit = models.FloatField(null=True, blank=True)
  stop = models.FloatField(null=True, blank=True)
  profit = models.IntegerField(null=True, blank=True)
  settlement_datetime = models.DateTimeField(null=True, blank=True)
  settlement_rate = models.FloatField(null=True, blank=True)

FX_project/Note/views.py
# 基本
import sys
import os
import pandas as pd
import datetime
from pytz import timezone
import calendar
# django
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Avg
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.urls import reverse
from django.db.models import Q
from django.db.models import Sum
# modelsとforms
from .models import HistoryTable, ChartTable, HistoryLinkTable, DiaryTable, ReviewTable, PositionTable
from .forms import ChartForm, DiaryForm, ReviewForm, ReviewUpdateForm, PositionSpeedForm, PositionMarketForm, PositionUpdateForm
# 独自関数
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
import lib.chart
import lib.chart_settings
# チャート出力用
import io
import base64
from matplotlib import use
use("Agg")
import mplfinance as mpf

# 曜日変換要
WEEK = ("月","火","水","木","金","土","日")

# html用
history_header = [
  "アカウント",
  "注文番号",
  "取引種類",
  "通貨ペア",
  "売買",
  "注文タイプ",
  "取引数量",
  "状態",
  "失効理由",
  "注文日時",
  "注文レート",
  "執行条件",
  "約定日時",
  "約定レート",
  "決済損益",
  "スワップ",
]
history_width = [
  100,  # アカウント
  80,  # 注文番号
  100,  # 取引種類
  100,  # 通貨ペア
  50,  # 売買
  100,  # 注文タイプ
  80,  # 取引数量
  100,  # 状態
  80,  # 失効理由
  200,  # 注文日時
  100,  # 注文レート
  80,  # 執行条件
  200,  # 約定日時
  100,  # 約定レート
  100,  # 決済損益
  100  # スワップ
]

RATE_DIR = os.path.join(os.path.dirname(__file__), "../data/rate") 

@login_required
def history(request):
  histories_all = HistoryTable.objects.filter(user=request.user).order_by("-order_number","-order_datetime")
  # paginator = Paginator(histories_all, 50)
  per_page = request.GET.get('per_page', 50)
  paginator = Paginator(histories_all, per_page)
  page = request.GET.get('page')
  histories = paginator.get_page(page)
  context = {
    "histories":histories, 
    "header":history_header, 
    "width":history_width,
    "box":True, 
    "checked":False
  }
  return render(request, 'Note/history.html', context)

@login_required
def chart_index(request):
  _charts = ChartTable.objects.filter(user=request.user).order_by("-id")
  links = [HistoryLinkTable.objects.filter(chart=i).count() for i in _charts]
  header = [
    "登録名",
    "通貨ペア",
    "足",
    "基準日時",
    "新規+決済",
    "操作"
  ]
  width = [
  200,  # 登録名
  100,  # 通貨ペア
  50,  # 足
  200,  # 基準日時
  100,  # 新規+決済
  100  # 操作
  ]
  context = {"charts":_charts, "links":links, "header":header, "width":width, "box":False, "checked":False}
  return render(request, 'Note/chart_index.html', context)

@login_required
def chart_image(request,id, _HttpResponse=True, _chart=None, histories=None):
  # 該当のchartのデータを取得
  if _chart == None:
    _chart = get_object_or_404(ChartTable, pk=id)
  # 該当のチャートと紐付けられている取引履歴を取得
  if histories == None:
    histories = [i.history for i in HistoryLinkTable.objects.filter(chart=_chart)]
    histories = sorted(histories, reverse=True, key=lambda x: x.id)
    histories = sorted(histories, reverse=True, key=lambda x: x.order_datetime)
  # 為替データを取得
  if "H" in _chart.rule:
    days = 40
  elif "D" in _chart.rule:
    days = 240
  else:
    days = 10
  df = lib.chart.GMO_dir2DataFrame(
    os.path.join(os.path.dirname(__file__), "../data/rate"), 
    pair=_chart.pair,
    date_range=[
      (_chart.standard_datetime-datetime.timedelta(days=days)).date(),
      (_chart.standard_datetime+datetime.timedelta(days=days)).date()
    ]
  ) 
  # 足を変換
  df = lib.chart.resample(df, _chart.rule)
  # テクニカル指標を追加
  df = lib.chart_settings.add_technical_columns(df)
  # 最もstandard_datetimeに近い列の周辺のデータを取得する
  target_datetime = pd.Timestamp(_chart.standard_datetime)
  nearest_index = (pd.DataFrame(df.index) - target_datetime).abs().idxmin().date
  start_index = max(0, nearest_index - _chart.minus_delta)
  end_index = min(nearest_index + _chart.plus_delta, len(df) - 1)
  df = df.iloc[start_index:end_index+1]
  
  ### チャートを作成
  # 共通部分
  plot_args = lib.chart_settings.plot_args.copy()
  # テクニカル指標を追加
  plot_args =  lib.chart_settings.add_technical_lines(plot_args, df)
  # 横線
  hlines=dict(hlines=[],colors=[],linewidths=[])
  for history in histories:
    if history.order_rate != None:
      hlines["hlines"].append(history.order_rate)
      if history.state == "canceled":
        hlines["colors"].append("#7d7d7d")
      elif history.buy_sell == "buy":
        hlines["colors"].append("r")
      else:
        hlines["colors"].append("b")
      hlines["linewidths"].append(0.1)
  plot_args["hlines"] = hlines
  # 取引期間
  # execution = [i.execution_datetime for i in histories if i.execution_datetime != None]
  # if len(execution) >= 2:
  #   transaction_start=pd.Timestamp(min(execution).astimezone(timezone("Asia/Tokyo")).strftime("%Y-%m-%d %H:%M"),tz=timezone("Asia/Tokyo"))
  #   transaction_end=pd.Timestamp(max(execution).astimezone(timezone("Asia/Tokyo")).strftime("%Y-%m-%d %H:%M"),tz=timezone("Asia/Tokyo"))
  #   dates_df = pd.DataFrame(df.index)
  #   where_values = pd.notnull(dates_df[(dates_df>=transaction_start)&(dates_df<=transaction_end)])['date'].values
  #   max_value = df["bb_up_3"].max(),
  #   min_value = df["bb_down_3"].min(),
  #   plot_args["fill_between"] = dict(y1=max_value, y2=min_value, where=where_values, alpha=0.3) 
  # 縦線
  vlines=dict(vlines=[],colors=[],linewidths=[])
  for history in histories:
    if history.execution_datetime != None and history.state != "canceled" and history.order_rate != None:
      vlines["vlines"].append(history.execution_datetime)
      if history.buy_sell == "buy":
        vlines["colors"].append("r")
      else:
        vlines["colors"].append("b")
      vlines["linewidths"].append(0.1)
  plot_args["vlines"] = vlines
  # 画像の大きさ
  plot_args["figsize"] = (14,8)
  # plot_args["figratio"] = (10,6)
  # 画像の出力先
  buf = io.BytesIO()
  plot_args["savefig"] = {'fname':buf,'dpi':100}
  # 出力
  mpf.plot(df, **plot_args)
  buf.seek(0)
  if _HttpResponse:
    return HttpResponse(buf, content_type='image/png')
  else:
    image_data = base64.b64encode(buf.getvalue()).decode("utf-8")
    return image_data
    # htmldjangoにおいて以下のように記述することで出力できる:
    # <img src="data:image/png;base64,{{ image_data  }}" alt="Chart">

@login_required
def chart_image_day(request, pair, year, month, day, _HttpResponse=True):
  pair = pair.replace("/","")
  dt = datetime.datetime(year, month, day)
  file = os.path.join(
    os.path.dirname(__file__), 
    "../data/rate", 
    pair,
    "{0}{1:02d}".format(year, month),
    "{0}_{1}{2:02d}{3:02d}.csv".format(pair, year, month, day)
  )
  if os.path.isfile(file):
    df = lib.chart.GMO_dir2DataFrame(
      os.path.join(os.path.dirname(__file__), "../data/rate"), 
      pair=pair,
      date_range=[
        (dt-datetime.timedelta(days=5)).date(), # 移動平均線等の計算のため，年末年始等にも対応して5日前から
        (dt+datetime.timedelta(days=1)).date()  # 未満のため+1
      ]
    ) 
    # 15分足
    df = lib.chart.resample(df, "15T")
    # テクニカル指標を追加
    df = lib.chart_settings.add_technical_columns(df)
    # 当日分
    df = df.iloc[-96:]
    ### チャートを作成
    # 共通部分
    plot_args = lib.chart_settings.plot_args.copy()
    # テクニカル指標を追加
    plot_args =  lib.chart_settings.add_technical_lines(plot_args, df)
    # 画像の大きさ
    plot_args["figsize"] = (10,6)
    # 画像の出力先
    buf = io.BytesIO()
    plot_args["savefig"] = {'fname':buf,'dpi':100}
    # タイトル
    # plot_args["title"] = f"{pair} 15T"
    # 出力
    mpf.plot(df, **plot_args)
    buf.seek(0)
    if _HttpResponse:
      return HttpResponse(buf, content_type='image/png')
    else:
      image_data = base64.b64encode(buf.getvalue()).decode("utf-8")
      return image_data
      # htmldjangoにおいて以下のように記述することで出力できる:
      # <img src="data:image/png;base64,{{ image_data  }}" alt="Chart">
  else:
    return None

@login_required
def chart_detail(request, id):
  # 該当のchartのデータを取得
  _chart = get_object_or_404(ChartTable, pk=id)
  form = ChartForm(instance=_chart)
  # 該当のチャートと紐付けられている取引履歴を取得
  histories = [i.history for i in HistoryLinkTable.objects.filter(chart=_chart)]
  histories = sorted(histories, reverse=True, key=lambda x: x.id)
  histories = sorted(histories, reverse=True, key=lambda x: x.order_datetime)
  image_data = chart_image(request, id, _HttpResponse=False, _chart=_chart, histories=histories)
  ### 渡すもの
  context = {
    "id": id,
    "chart":_chart,
    "histories":histories, 
    "image_data":image_data,
    "form":form,
    "header":history_header, 
    "width":history_width,
    "box":False, 
    "checked":False,
  }
  return render(request, 'Note/chart_detail.html', context)

@login_required
def histories2edit(request):
  histories = HistoryTable.objects.filter(
    id__in=request.POST.getlist("register")).order_by("-order_number","-order_datetime"
  )
  dts = [i[0].timestamp() for i in histories.values_list("execution_datetime") if i[0] != None]
  if len(dts) == 0:
    dts = [i[0].timestamp() for i in histories.values_list("order_datetime") if i[0] != None]
  timezones = [i[0].tzinfo for i in histories.values_list("execution_datetime") if i[0] != None]
  if len(timezones) != timezones.count(timezones[0]):
    raise Exception
  pairs = [i[0] for i in histories.values_list("pair")]
  if len(pairs) != pairs.count(pairs[0]):
    raise Exception
  ave = datetime.datetime.fromtimestamp(sum(dts)/len(dts),tz=timezones[0])
  initial = {
    # "user":request.user,
    "pair":pairs[0],
    "standard_datetime": ave,
    "plus_delta":100,
    "minus_delta":100
  }
  form = ChartForm(initial=initial)
  context = {
    "histories":histories,
    "header":history_header,
    "width":history_width,
    "form":form,
    "table":True,
    "box":True, 
    "checked":True,
  }
  return render(request, 'Note/edit.html', context)

@login_required
def none2edit(request):
  initial = {
    "plus_delta":100,
    "minus_delta":100
  }
  form = ChartForm(initial=initial)
  context = {
    "form":form,
    "table":False,
  }
  return render(request, 'Note/edit.html', context)

@login_required
def chart_add(request):
  form = ChartForm(request.POST)

FX_project/templates/Note/calendar.html
{% extends 'base.html' %}
{% load boost %}
{% block title %}カレンダー{% endblock title %}
{% block content %}
<h1 class="text-center">
<a href='{% url "Note:calendar" prev.year prev.month %}'> << </a>
{{year}}年{{month}}月
<a href='{% url "Note:calendar" next.year next.month %}'> >> </a>
</h1>
</div>
<div class="table-responsive">
  <table class="table table-bordered border-dark" style="table-layout:fixed;">
    <tbody>
    {% for calendar_row in calendar %}
      <tr>
        {% for i in calendar_row %}
        {% if i != "" and i not in calendar.0 %}
        {% if i == today %}
        <th scope="col" class="table-primary">
        {% else %}
        <th scope="col">
        {% endif %}
          <div class="d-grid gap-2">
            {% if i == calendar_row.0 %}
            <a href='{% url "Note:diary" year month i %}' class="btn btn-danger btn-sm">{{ i }}</a>
            {# <div class="btn btn-danger btn-sm">{{ i }}</div> #}
            {% elif i == calendar_row.6 %}
            <a href='{% url "Note:diary" year month i %}' class="btn btn-primary btn-sm">{{ i }}</a>
            {# <div class="btn btn-primary btn-sm">{{ i }}</div> #}
            {% else %}
            <a href='{% url "Note:diary" year month i %}' class="btn btn-success btn-sm">{{ i }}</a>
            {# <div class="btn btn-success btn-sm">{{ i }}</div> #}
            {% endif %}
            {% if request.user.is_authenticated %}
            {% endif %}
          </div>
        {% else %}
        <th scope="col" class="text-center">
          {{ i }}
          {% endif %}
        </th>
        {% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

FX_project/templates/Note/chart.html
{% extends 'base.html' %}
{% block title %}取引履歴{% endblock title %}
{% block content %}
<div class="table-responsive">
  <table class="table table-bordered border-dark text-nowrap" style="table-layout:fixed;">
    <tbody>
      <tr class="table-warning text-center">
        <th scope="col" style="width: 200px;">
          登録名 
        </th>
        <th scope="col" style="width: 100px;">
          通貨ペア
        </th>
        <th scope="col" style="width: 100px;">
          足
        </th>
        <th scope="col" style="width: 500px;">
          メモ
        </th>
        <th scope="col" style="width: 100px;">
          操作
        </th>
      </tr>
      <tr class="text-center">
        <td>
          {{ chart.name }}
        </td>
        <td>
          {{ chart.pair }}
        </td>
        <td>
          {{ chart.rule }}
        </td>
        <td>
          {% if chart.memo != None %}
          {{ chart.memo }}
          {% endif %}
        </td>
        <td>
          <a class="btn btn-primary btn-sm" href='{% url "Note:chart_edit" id %}'>編集</a>
        </td>
      </tr>
    </tbody>
  </table>
 </div>
<div class="col" style="overflow-x: auto;">
  <img src="data:image/png;base64,{{ image_data  }}" alt="Chart">
</div>
{% include 'Note/history_table_jp.html' %}
{# <form class="" action="{% url 'Note:chart_update' id %}" method="post"> #}
{#   {% csrf_token %} #}
{#   {{ form.as_p }} #}
{#   {% include 'Note/history_table_jp.html' %} #}
{#   <button type="submit" class="btn btn-primary btn-sm">登録</button> #}
{# </form> #}
{% endblock content %}

FX_project/templates/Note/chart_detail.html
{% extends 'base.html' %}
{% block title %}チャート{% endblock title %}
{% block content %}
<div class="container-fluid custom-container">
  <div class="row">
    <div class="col-9">
      <h3 class="text-center">{{ chart.pair }} {{ chart.get_rule_display }}</h3>
      <div class="col" style="overflow-x: auto;">
        <a href="{% url "Note:chart_image" id %}">
           <img src="data:image/png;base64,{{ image_data  }}" alt="Chart">
        </a>
      </div>
    </div>
    <div class="col">
      <form class="" action="{% url 'Note:chart_update' id %}" method="post">
        {% csrf_token %}
        {# {{ form.as_p }} #}
        <p>
          保存名：{{ form.name }}
        </p>
        <p>
          基準時刻：{{ form.standard_datetime }}
        </p>
        <p>
          足：{{ form.rule }}
        </p>
        <p>
          通貨ペア：{{ form.pair }}
        </p>
        <p>
          正方向表示本数：{{ form.plus_delta }}
        </p>
        <p>
          負方向表示本数：{{ form.minus_delta }}
        </p>
        <p>
          説明：
        </p>
          {{ form.memo }}
        <p>
          <button type="submit" class="btn btn-primary btn-sm">更新</button>
          <a href="{% url 'Note:chart_delete' id %}" class="btn btn-danger btn-sm">削除</a>
        </p>
      </form>
    </div>
  </div>
</div>
{% include 'Note/history_table_jp.html' %}
{% endblock content %}

FX_project/templates/Note/chart_index.html
{% extends 'base.html' %}
{% load boost %}

{% block title %}チャート一覧{% endblock title %}
{% block content %}
<h1>チャート</h1><nobr>
<a href='{% url "Note:chart_create" %}' class="btn btn-success btn">新規作成</a>
<div class="table-responsive">
  <table class="table table-bordered border-dark text-nowrap" style="table-layout:fixed;">
    <tbody>
      <tr class="table-warning text-center">
        {% for h,w in header|zip:width %}
        <th scope="col" style="width: {{ w }}px;">
            {{ h }}
        </th>
        {% endfor %}
      </tr>
      {% for chart,link in charts|zip:links %}
      <tr class="text-center">
        <td>
          {{ chart.name }}
        </td>
        <td>
          {{ chart.pair }}
        </td>
        <td>
          {{ chart.rule }}
        </td>
        <td>
          {{ chart.standard_datetime }}
        </td>
        <td>
          {{ link }}
        </td>
        <td>
          <a href='{% url "Note:chart_detail" chart.id %}' class="btn btn-sm btn-danger btn">開く</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock content %}

FX_project/templates/Note/diary.html
{% extends 'base.html' %}
{% block title %}日記{% endblock title %}
{% block content %}
<div class="container-fluid custom-container">
  <div class="row">
    <div class="col-8">
      {% include 'Note/chart_tab.html' %}
    </div>
    <div class="col">
      <h1 class="text-center">
        <a href="{{ prev_link }}"> << </a>
        {{ year }}年{{ month }}月{{ day }}日 ({{ weekday }})
        <a href="{{ next_link }}"> >> </a>
      </h1>
      {% if option == "edit" %}
      {% if type == "add" %}
      <form class="" action="{% url 'Note:diary_create' year month day %}" method="post">
      {% elif type == "update" %}
      <form class="" action="{% url 'Note:diary_update' obj.id %}" method="post">
      {% else %}
      <form class="" action="{% url 'Note:diary_create' year month day %}" method="post">
      {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        {% if type == "add" %}
        <button type="submit" class="btn btn-primary btn-sm">登録</button>
        {% elif type == "update" %}
        <button type="submit" class="btn btn-primary btn-sm">更新</button>
        <a href="{% url 'Note:diary_delete' obj.id %}" class="btn btn-primary btn-sm">削除</a>
        {% else %}
        <button type="submit" class="btn btn-primary btn-sm">登録</button>
        {% endif %}
      </form>
      {% else %}
      <div class="card" style="width: 100%;">
        <div class="card-body">
          {% if obj == None %}
          日記が存在しません．
          {% else %}
          {{ obj.text }}
          {% endif %}
        </div>
      </div>
      <div class="d-flex justify-content-end">
        {% if obj == None %}
        <a href="{% url 'Note:diary_option' year month day "edit" %}" class="btn btn-primary btn-sm">作成</a>
        {% else %}
        <a href="{% url 'Note:diary_option' year month day "edit" %}" class="btn btn-primary btn-sm">編集</a>
        {% endif %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

FX_project/templates/Note/review_index.html
{% extends 'base.html' %}
{% load boost %}

{% block title %}レビュー一覧{% endblock title %}
{% block content %}
<h1>レビュー</h1><nobr>
<a href='{% url "Note:review_create" %}' class="btn btn-success btn">新規作成</a>
{% for review in reviews %}
<div class="card">
  <h5 class="card-header">{{ review.dt }}</h5>
  <div class="card-body">
    <h5 class="card-title">{{ review.name }}</h5>
    <p class="card-text">{{ review.memo }}</p>
    <a href="{% url 'Note:review' review.id %}" class="btn btn-primary">開く</a>
  </div>
</div>
{% endfor %}

{% endblock content %}